import * as THREE from 'three';
import {changanCity} from '../data/changanCity';
import {createHistoricalMaterialLibrary} from './HistoricalAssets';
import {createFullCitySet} from './FullCityAssets';
import {compactInstancesExcluding,NORTH_GATE_SOURCE_ID} from './TaijiInstanceFilter';

it('tags every full-city and ordinary-detail batch instance generated by the north gate',()=>{
  const root=createFullCitySet(createHistoricalMaterialLibrary(),changanCity);const tagged:THREE.InstancedMesh[]=[];
  root.traverse(o=>{if(o instanceof THREE.InstancedMesh&&(o.userData.sourceIds as unknown[]|undefined)?.includes(NORTH_GATE_SOURCE_ID))tagged.push(o);});
  expect(tagged.map(mesh=>mesh.name)).toEqual(expect.arrayContaining([
    'full-city-building-body-dark','full-city-building-roof-dark','ordinary-ward-foundations','ordinary-ward-roof-slopes','ordinary-ward-roof-ridges','ordinary-ward-eaves','ordinary-ward-timber-columns','ordinary-ward-timber-lintels','ordinary-ward-door-panels','ordinary-ward-window-panels','ordinary-ward-thresholds','ordinary-ward-courtyard-paving','ordinary-ward-pottery-jars'
  ]));
  expect(tagged.every(mesh=>(mesh.userData.sourceIds as unknown[]).length===mesh.count)).toBe(true);
});

it('compacts matrices and colors under a transformed hierarchy without mutating borrowed sources and restores visibility',()=>{
  const outer=new THREE.Group();outer.position.set(17,3,-8);outer.rotation.y=.4;const root=new THREE.Group();root.position.set(5,2,9);root.scale.set(1.2,.8,1.1);outer.add(root);
  const nested=new THREE.Group();nested.position.set(-2,1,4);root.add(nested);
  const mesh=new THREE.InstancedMesh(new THREE.BoxGeometry(),new THREE.MeshBasicMaterial(),3);mesh.name='colored';mesh.userData.sourceIds=['keep-a',NORTH_GATE_SOURCE_ID,'keep-b'];
  const m=new THREE.Matrix4();for(let i=0;i<3;i++){mesh.setMatrixAt(i,m.makeTranslation(i*3,i,-i));mesh.setColorAt(i,new THREE.Color(i/4,.3,.7));}nested.add(mesh);outer.updateMatrixWorld(true);
  const matrices=new Float32Array(mesh.instanceMatrix.array),colors=new Float32Array(mesh.instanceColor!.array),worldBefore=mesh.matrixWorld.clone();
  const replacement=compactInstancesExcluding(root,NORTH_GATE_SOURCE_ID);root.add(replacement.group);outer.updateMatrixWorld(true);
  const copy=replacement.group.getObjectByName('compacted-colored') as THREE.InstancedMesh;expect(copy.count).toBe(2);expect(copy.geometry).toBe(mesh.geometry);expect(copy.material).toBe(mesh.material);
  copy.matrixWorld.elements.forEach((value,index)=>expect(value).toBeCloseTo(worldBefore.elements[index],6));expect(Array.from(mesh.instanceMatrix.array)).toEqual(Array.from(matrices));expect(Array.from(mesh.instanceColor!.array)).toEqual(Array.from(colors));
  const c=new THREE.Color();copy.getColorAt(1,c);const expected=new THREE.Color();mesh.getColorAt(2,expected);expect(c.toArray()).toEqual(expected.toArray());
  expect(mesh.visible).toBe(false);replacement.restore();expect(mesh.visible).toBe(true);replacement.restore();expect(mesh.visible).toBe(true);
});

it('keeps an originally invisible tagged batch and its compact copy invisible',()=>{
  const root=new THREE.Group(),mesh=new THREE.InstancedMesh(new THREE.BoxGeometry(),new THREE.MeshBasicMaterial(),2);
  mesh.visible=false;mesh.userData.sourceIds=['keep',NORTH_GATE_SOURCE_ID];root.add(mesh);
  const replacement=compactInstancesExcluding(root,NORTH_GATE_SOURCE_ID);root.add(replacement.group);
  expect(replacement.group.children[0].visible).toBe(false);expect(mesh.visible).toBe(false);
  replacement.restore();expect(mesh.visible).toBe(false);
});
